name: Mage-OS Validations
on: [push, pull_request]

jobs:
  directory-validation:
    name: Directory CSV validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl-70.1
      - uses: php-actions/composer@v6
      - run: php bin/directory-validation.php
